# Generated by Django 6.0.4 on 2026-05-15 13:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization_scope(apps, schema_editor):
    Branch = apps.get_model("users", "Branch")
    Organization = apps.get_model("users", "Organization")
    Category = apps.get_model("inventory", "Category")
    Supplier = apps.get_model("inventory", "Supplier")
    Product = apps.get_model("inventory", "Product")
    InventoryTransaction = apps.get_model("inventory", "InventoryTransaction")
    BranchStock = apps.get_model("inventory", "BranchStock")

    organizations = list(Organization.objects.order_by("id"))
    if not organizations:
        has_legacy_inventory = (
            Category.objects.exists()
            or Supplier.objects.exists()
            or Product.objects.exists()
            or InventoryTransaction.objects.exists()
        )
        if has_legacy_inventory:
            raise RuntimeError(
                "Legacy inventory records exist without an organization. "
                "Create an organization before applying inventory multi-tenant migration."
            )
        return

    if len(organizations) > 1:
        has_unscoped_inventory = (
            Category.objects.filter(organization__isnull=True).exists()
            or Supplier.objects.filter(organization__isnull=True).exists()
            or Product.objects.filter(organization__isnull=True).exists()
            or InventoryTransaction.objects.filter(organization__isnull=True).exists()
        )
        if has_unscoped_inventory:
            raise RuntimeError(
                "Cannot safely assign legacy inventory data across multiple organizations automatically."
            )

    default_organization = organizations[0]
    default_branch = (
        Branch.objects.filter(organization=default_organization, is_main=True).first()
        or Branch.objects.filter(organization=default_organization).order_by("id").first()
    )
    if default_branch is None:
        raise RuntimeError(
            "A main branch is required before inventory scope can be backfilled."
        )

    Category.objects.filter(organization__isnull=True).update(
        organization=default_organization
    )
    Supplier.objects.filter(organization__isnull=True).update(
        organization=default_organization
    )
    Product.objects.filter(organization__isnull=True).update(
        organization=default_organization
    )

    for product in Product.objects.select_related("organization").all():
        branch = (
            Branch.objects.filter(organization=product.organization, is_main=True).first()
            or default_branch
        )
        BranchStock.objects.update_or_create(
            product=product,
            branch=branch,
            defaults={
                "current_stock": product.current_stock,
                "reorder_level": product.reorder_level,
            },
        )

    for transaction in InventoryTransaction.objects.select_related("product__organization").all():
        organization = transaction.organization or transaction.product.organization
        if organization is None:
            organization = default_organization

        branch = transaction.branch
        if branch is None:
            branch = (
                Branch.objects.filter(organization=organization, is_main=True).first()
                or default_branch
            )

        transaction.organization = organization
        transaction.branch = branch
        transaction.save(update_fields=["organization", "branch"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction'),
        ('users', '0003_branch_userprofile_active_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='users.organization'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='users.branch'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('agency', 'Agency')], default='owned', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='users.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.product')),
            ],
            options={
                'ordering': ['branch__name'],
                'unique_together': {('product', 'branch')},
            },
        ),
        migrations.RunPython(backfill_organization_scope, migrations.RunPython.noop),
    ]
