# Generated by Django 6.0.4 on 2026-05-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sale_scope(apps, schema_editor):
    Branch = apps.get_model("users", "Branch")
    Organization = apps.get_model("users", "Organization")
    Sale = apps.get_model("sales", "Sale")

    organizations = list(Organization.objects.order_by("id"))
    if not organizations:
        if Sale.objects.exists():
            raise RuntimeError(
                "Legacy sales records exist without an organization. "
                "Create an organization before applying sales multi-tenant migration."
            )
        return

    if len(organizations) > 1 and Sale.objects.filter(organization__isnull=True).exists():
        raise RuntimeError(
            "Cannot safely assign legacy sales data across multiple organizations automatically."
        )

    default_organization = organizations[0]
    default_branch = (
        Branch.objects.filter(organization=default_organization, is_main=True).first()
        or Branch.objects.filter(organization=default_organization).order_by("id").first()
    )
    if default_branch is None:
        raise RuntimeError(
            "A main branch is required before sales scope can be backfilled."
        )

    for sale in Sale.objects.all().order_by("created_at", "id"):
        organization = sale.organization or default_organization
        branch = sale.branch or (
            Branch.objects.filter(organization=organization, is_main=True).first()
            or default_branch
        )

        sale.organization = organization
        sale.branch = branch
        if not sale.receipt_number:
            sale.receipt_number = f"LEGACY-{sale.id:06d}"
        if sale.is_paid:
            sale.amount_paid = sale.total_amount
            sale.balance_due = 0
            sale.payment_status = "paid"
        else:
            sale.amount_paid = 0
            sale.balance_due = sale.total_amount
            sale.payment_status = "unpaid"
        if sale.created_by_id is None:
            sale.created_by = organization.created_by
        sale.save(
            update_fields=[
                "organization",
                "branch",
                "receipt_number",
                "amount_paid",
                "balance_due",
                "payment_status",
                "created_by",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_amount'),
        ('users', '0003_branch_userprofile_active_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.organization'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(backfill_sale_scope, migrations.RunPython.noop),
    ]
