# Generated by Django 6.0.4 on 2026-05-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_main_branches(apps, schema_editor):
    Branch = apps.get_model("users", "Branch")
    Organization = apps.get_model("users", "Organization")
    OrganizationMembership = apps.get_model("users", "OrganizationMembership")
    UserProfile = apps.get_model("users", "UserProfile")

    for organization in Organization.objects.all():
        main_branch = Branch.objects.filter(
            organization=organization,
            is_main=True,
        ).first()
        if main_branch is None:
            main_branch = Branch.objects.create(
                organization=organization,
                name="Main Branch",
                code="MAIN",
                is_main=True,
                is_active=True,
                created_by=organization.created_by,
            )

        for profile in UserProfile.objects.filter(active_organization=organization):
            if profile.active_branch_id is None:
                profile.active_branch = main_branch
                profile.save(update_fields=["active_branch"])

    for profile in UserProfile.objects.filter(active_organization__isnull=True):
        membership_ids = list(
            OrganizationMembership.objects.filter(user=profile.user)
            .values_list("organization_id", flat=True)[:2]
        )
        if len(membership_ids) != 1:
            continue

        organization = Organization.objects.get(pk=membership_ids[0])
        main_branch = Branch.objects.filter(
            organization=organization,
            is_main=True,
        ).first()
        profile.active_organization = organization
        profile.active_branch = main_branch
        profile.save(update_fields=["active_organization", "active_branch"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_join_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='users.branch'),
        ),
        migrations.RunPython(create_main_branches, migrations.RunPython.noop),
    ]
