# Generated by Django 6.0.4 on 2026-05-15 15:24

from django.db import migrations, models


def assign_default_module_access(apps, schema_editor):
    OrganizationMembership = apps.get_model("users", "OrganizationMembership")

    default_by_role = {
        "owner": ["home", "dashboard", "pos", "inventory", "settings", "users"],
        "admin": ["home", "dashboard", "pos", "inventory", "settings", "users"],
        "member": ["home", "dashboard", "pos"],
    }

    for membership in OrganizationMembership.objects.all():
        membership.module_access = default_by_role.get(
            membership.role,
            ["home", "dashboard"],
        )
        membership.save(update_fields=["module_access"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_branch_userprofile_active_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='module_access',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(assign_default_module_access, migrations.RunPython.noop),
    ]
